-- Rename the column with typo RECOHIDO to RECOLHIDO
ALTER TABLE "public"."BANCO_DE_DADOS" RENAME COLUMN "RECOHIDO" TO "RECOLHIDO";

-- Set ID VENDA ITENS as Identity Column (Auto Increment)
ALTER TABLE "public"."BANCO_DE_DADOS" ALTER COLUMN "ID VENDA ITENS" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Sync the sequence to the current max value to avoid conflicts with existing IDs
DO $$
DECLARE
    max_id INTEGER;
BEGIN
    SELECT COALESCE(MAX("ID VENDA ITENS"), 0) + 1 INTO max_id FROM "public"."BANCO_DE_DADOS";
    EXECUTE 'ALTER TABLE "public"."BANCO_DE_DADOS" ALTER COLUMN "ID VENDA ITENS" RESTART WITH ' || max_id;
END $$;
