CREATE TABLE IF NOT EXISTS "RECEBIMENTOS" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venda_id" bigint NOT NULL,
  "cliente_id" bigint NOT NULL REFERENCES "CLIENTES"("CODIGO"),
  "forma_pagamento" text NOT NULL,
  "valor_pago" numeric NOT NULL,
  "data_pagamento" timestamp with time zone DEFAULT now(),
  "funcionario_id" bigint NOT NULL REFERENCES "FUNCIONARIOS"("id"),
  "created_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE "RECEBIMENTOS" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users" ON "RECEBIMENTOS"
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
