-- Add HORA DO ACERTO and VALENTIA columns to BANCO_DE_DADOS
ALTER TABLE "public"."BANCO_DE_DADOS" ADD COLUMN IF NOT EXISTS "HORA DO ACERTO" text;
ALTER TABLE "public"."BANCO_DE_DADOS" ADD COLUMN IF NOT EXISTS "VALENTIA" text;
