CREATE TABLE IF NOT EXISTS public.dre_lancamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mes_referencia TEXT NOT NULL,
    data_lancamento DATE NOT NULL,
    tipo TEXT NOT NULL,
    categoria TEXT,
    valor NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.dre_categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    tipo TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed basic categories
INSERT INTO public.dre_categorias (nome, tipo) VALUES
('Aluguel', 'CUSTO_FIXO'),
('Energia', 'CUSTO_FIXO'),
('Água', 'CUSTO_FIXO'),
('Internet/Telefone', 'CUSTO_FIXO'),
('Contabilidade', 'CUSTO_FIXO'),
('Folha de Pagamento', 'CUSTO_FIXO'),
('Marketing', 'CUSTO_FIXO'),
('Limpeza', 'CUSTO_FIXO')
ON CONFLICT (nome) DO NOTHING;

-- Grant access to authenticated users
ALTER TABLE public.dre_lancamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dre_categorias ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated users on dre_lancamentos"
    ON public.dre_lancamentos FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable all for authenticated users on dre_categorias"
    ON public.dre_categorias FOR ALL TO authenticated USING (true) WITH CHECK (true);
