CREATE TABLE IF NOT EXISTS "fechamento_caixa" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rota_id BIGINT REFERENCES "ROTA"(id) NOT NULL,
  funcionario_id BIGINT REFERENCES "FUNCIONARIOS"(id) NOT NULL,
  venda_total NUMERIC DEFAULT 0,
  desconto_total NUMERIC DEFAULT 0,
  valor_a_receber NUMERIC DEFAULT 0,
  valor_dinheiro NUMERIC DEFAULT 0,
  valor_pix NUMERIC DEFAULT 0,
  valor_cheque NUMERIC DEFAULT 0,
  dinheiro_aprovado BOOLEAN DEFAULT FALSE,
  pix_aprovado BOOLEAN DEFAULT FALSE,
  cheque_aprovado BOOLEAN DEFAULT FALSE,
  responsavel_id BIGINT REFERENCES "FUNCIONARIOS"(id),
  status TEXT DEFAULT 'Aberto',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_fechamento_caixa_rota_id ON "fechamento_caixa"(rota_id);
CREATE INDEX IF NOT EXISTS idx_fechamento_caixa_funcionario_id ON "fechamento_caixa"(funcionario_id);
