-- Create KITS table
CREATE TABLE IF NOT EXISTS kits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create KIT_ITEMS table
CREATE TABLE IF NOT EXISTS kit_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kit_id BIGINT NOT NULL REFERENCES kits(id) ON DELETE CASCADE,
  produto_id BIGINT NOT NULL REFERENCES "PRODUTOS"("ID") ON DELETE CASCADE,
  quantidade_padrao NUMERIC NOT NULL DEFAULT 1
);

-- Create function to handle x_na_rota logic
CREATE OR REPLACE FUNCTION update_x_na_rota()
RETURNS TRIGGER AS $$
BEGIN
  -- Manual Override Check: If x_na_rota is explicitly changed in the UPDATE, do nothing (respect manual change)
  IF NEW.x_na_rota IS DISTINCT FROM OLD.x_na_rota THEN
    RETURN NEW;
  END IF;

  -- Logic: Seller Assigned (Null -> Value) -> Increment
  IF OLD.vendedor_id IS NULL AND NEW.vendedor_id IS NOT NULL THEN
    NEW.x_na_rota := COALESCE(OLD.x_na_rota, 0) + 1;
  -- Logic: Seller Removed (Value -> Null) -> Decrement
  ELSIF OLD.vendedor_id IS NOT NULL AND NEW.vendedor_id IS NULL THEN
    NEW.x_na_rota := GREATEST(0, COALESCE(OLD.x_na_rota, 0) - 1);
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create Trigger on ROTA_ITEMS
DROP TRIGGER IF EXISTS tr_update_x_na_rota ON "ROTA_ITEMS";
CREATE TRIGGER tr_update_x_na_rota
BEFORE UPDATE ON "ROTA_ITEMS"
FOR EACH ROW
EXECUTE FUNCTION update_x_na_rota();
