CREATE TABLE IF NOT EXISTS public.dividas_manuais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cobranca_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
  funcionario_id BIGINT REFERENCES public."FUNCIONARIOS"(id) ON DELETE SET NULL,
  cliente_id BIGINT REFERENCES public."CLIENTES"("CODIGO") ON DELETE CASCADE,
  data_acerto DATE NOT NULL,
  vencimento DATE NOT NULL,
  forma_pagamento TEXT NOT NULL,
  valor_parcela NUMERIC NOT NULL DEFAULT 0,
  valor_pago NUMERIC NOT NULL DEFAULT 0,
  forma_cobranca TEXT,
  data_combinada DATE,
  motivo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.dividas_manuais ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.dividas_manuais;
CREATE POLICY "Enable all access for authenticated users" ON public.dividas_manuais
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.dividas_manuais_acoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  divida_id BIGINT REFERENCES public.dividas_manuais(id) ON DELETE CASCADE,
  funcionario_id BIGINT REFERENCES public."FUNCIONARIOS"(id) ON DELETE SET NULL,
  acao TEXT NOT NULL,
  data_acao TIMESTAMPTZ DEFAULT NOW(),
  nova_data_combinada DATE,
  motivo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.dividas_manuais_acoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.dividas_manuais_acoes;
CREATE POLICY "Enable all access for authenticated users" ON public.dividas_manuais_acoes
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
