-- Migration to ensure ID VENDA ITENS in BANCO_DE_DADOS is handled as identity column
-- This prevents "null value violates not-null constraint" errors during inserts

DO $$
BEGIN
    -- Check if the column is already an identity column
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'BANCO_DE_DADOS'
          AND column_name = 'ID VENDA ITENS'
          AND is_identity = 'YES'
    ) THEN
        -- If it's a serial or has a default, drop it first to convert to identity safely
        ALTER TABLE "public"."BANCO_DE_DADOS" ALTER COLUMN "ID VENDA ITENS" DROP DEFAULT;
        
        -- Make it an identity column
        ALTER TABLE "public"."BANCO_DE_DADOS" ALTER COLUMN "ID VENDA ITENS" 
        ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
    
    -- Sync the sequence to the current max value
    -- Dynamic SQL is used because the sequence name depends on the column identity
    EXECUTE 'SELECT setval(pg_get_serial_sequence(''"public"."BANCO_DE_DADOS"'', ''ID VENDA ITENS''), COALESCE(MAX("ID VENDA ITENS"), 0) + 1, false) FROM "public"."BANCO_DE_DADOS"';
    
EXCEPTION WHEN OTHERS THEN
    -- Fallback for sequence syncing if pg_get_serial_sequence returns null (rare edge case)
    NULL;
END $$;
