CREATE TABLE IF NOT EXISTS public.boletos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_nome TEXT NOT NULL,
    cliente_codigo BIGINT NOT NULL REFERENCES public."CLIENTES"("CODIGO") ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'A Receber',
    vencimento DATE NOT NULL,
    valor NUMERIC NOT NULL,
    pedido_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.boletos ENABLE ROW LEVEL SECURITY;

-- Create Policy
CREATE POLICY "Enable all for authenticated users" ON public.boletos
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Add indexes for better query performance on filtering and matching
CREATE INDEX IF NOT EXISTS idx_boletos_cliente_codigo ON public.boletos(cliente_codigo);
CREATE INDEX IF NOT EXISTS idx_boletos_vencimento ON public.boletos(vencimento);
