ALTER TABLE public."DESPESAS"
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'A confirmar',
ADD COLUMN IF NOT EXISTS banco_pagamento TEXT,
ADD COLUMN IF NOT EXISTS banco_outro TEXT,
ADD COLUMN IF NOT EXISTS data_lancamento DATE;
