-- Add ID_da_fêmea column to RECEBIMENTOS if it doesn't exist
-- This column is used for Order Number as per requirements
ALTER TABLE "public"."RECEBIMENTOS" ADD COLUMN IF NOT EXISTS "ID_da_fêmea" BIGINT;

-- Backfill ID_da_fêmea with venda_id for existing records to ensure gallery is not empty
UPDATE "public"."RECEBIMENTOS" SET "ID_da_fêmea" = "venda_id" WHERE "ID_da_fêmea" IS NULL;

-- Ensure PIX table exists with correct columns
CREATE TABLE IF NOT EXISTS "public"."PIX" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "recebimento_id" BIGINT NOT NULL REFERENCES "public"."RECEBIMENTOS"("id") ON DELETE CASCADE,
    "nome_no_pix" TEXT,
    "banco_pix" TEXT,
    "data_pix_realizado" TIMESTAMP WITH TIME ZONE,
    "confirmado_por" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT "PIX_recebimento_id_key" UNIQUE ("recebimento_id")
);

-- Enable RLS
ALTER TABLE "public"."PIX" ENABLE ROW LEVEL SECURITY;

-- Policies for PIX
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'PIX' AND policyname = 'Enable all for authenticated users') THEN
        CREATE POLICY "Enable all for authenticated users" ON "public"."PIX" FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;
