ALTER TABLE public."CLIENTES" ADD COLUMN IF NOT EXISTS latitude NUMERIC(10, 8);
ALTER TABLE public."CLIENTES" ADD COLUMN IF NOT EXISTS longitude NUMERIC(11, 8);
ALTER TABLE public."CLIENTES" ADD COLUMN IF NOT EXISTS favorito BOOLEAN DEFAULT FALSE;

