-- Create Suppliers Table
CREATE TABLE IF NOT EXISTS "FORNECEDORES" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_fornecedor TEXT NOT NULL,
    cnpj TEXT,
    endereco TEXT,
    telefone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Inventory Management Tables
CREATE TABLE IF NOT EXISTS "ID Inventário" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_inicio TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    data_fim TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'ABERTO'
);

CREATE TABLE IF NOT EXISTS "ESTOQUE GERAL SALDO INICIAL" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario BIGINT REFERENCES "ID Inventário"(id),
    pedido_id BIGINT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    funcionario TEXT,
    codigo_produto BIGINT,
    barcode TEXT,
    produto TEXT,
    preco NUMERIC(10,2),
    saldo_inicial NUMERIC(10,2) DEFAULT 0,
    produto_id BIGINT -- FK to PRODUTOS for join convenience
);

CREATE TABLE IF NOT EXISTS "ESTOQUE GERAL COMPRAS" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario BIGINT REFERENCES "ID Inventário"(id),
    produto_id BIGINT,
    fornecedor_id BIGINT REFERENCES "FORNECEDORES"(id),
    fornecedor_nome TEXT,
    compras_quantidade NUMERIC(10,2) DEFAULT 0,
    valor_unitario NUMERIC(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS "ESTOQUE GERAL CARRO PARA ESTOQUE" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario BIGINT REFERENCES "ID Inventário"(id),
    produto_id BIGINT,
    quantidade NUMERIC(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS "ESTOQUE GERAL SAÍDAS PERDAS" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario BIGINT REFERENCES "ID Inventário"(id),
    produto_id BIGINT,
    quantidade NUMERIC(10,2) DEFAULT 0,
    motivo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS "ESTOQUE GERAL ESTOQUE PARA CARRO" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario BIGINT REFERENCES "ID Inventário"(id),
    produto_id BIGINT,
    quantidade NUMERIC(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS "ESTOQUE GERAL CONTAGEM" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario BIGINT REFERENCES "ID Inventário"(id),
    produto_id BIGINT,
    quantidade NUMERIC(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS "ESTOQUE GERAL AJUSTES" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inventario BIGINT REFERENCES "ID Inventário"(id),
    produto_id BIGINT,
    ajuste_quantidade NUMERIC(10,2) DEFAULT 0,
    novo_saldo_final NUMERIC(10,2) DEFAULT 0,
    diferenca_quantidade NUMERIC(10,2) DEFAULT 0,
    diferenca_valor NUMERIC(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Helper view for inventory dashboard aggregation (Optional but good practice, doing logic in Service for now as requested)
