-- Create table for Pendency annotations
CREATE TABLE IF NOT EXISTS public.pendencia_anotacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pendencia_id BIGINT REFERENCES public."PENDENCIAS"(id) ON DELETE CASCADE,
    funcionario_id BIGINT REFERENCES public."FUNCIONARIOS"(id) ON DELETE SET NULL,
    texto TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for the new table
ALTER TABLE public.pendencia_anotacoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for all users" ON public.pendencia_anotacoes;
CREATE POLICY "Enable all access for all users" ON public.pendencia_anotacoes 
    FOR ALL USING (true) WITH CHECK (true);

-- Add login_count to FUNCIONARIOS if it doesn't exist
ALTER TABLE public."FUNCIONARIOS" ADD COLUMN IF NOT EXISTS login_count INTEGER DEFAULT 0;

-- Insert default configurations for indicators
INSERT INTO public.configuracoes (chave, valor) VALUES 
    ('dias_notificacao_pendencia', '5'),
    ('logins_para_notificacao', '3')
ON CONFLICT (chave) DO NOTHING;
