CREATE TABLE IF NOT EXISTS rota_motoqueiro_km (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  data_hora TIMESTAMPTZ NOT NULL,
  km_percorrido NUMERIC NOT NULL,
  funcionario_id BIGINT NOT NULL REFERENCES "FUNCIONARIOS" (id)
);

ALTER TABLE rota_motoqueiro_km ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON rota_motoqueiro_km FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON rota_motoqueiro_km FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users" ON rota_motoqueiro_km FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users" ON rota_motoqueiro_km FOR DELETE USING (auth.role() = 'authenticated');

