CREATE TABLE IF NOT EXISTS "PENDENCIAS" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES "CLIENTES"("CODIGO"),
    funcionario_id BIGINT NOT NULL REFERENCES "FUNCIONARIOS"(id),
    descricao_pendencia TEXT NOT NULL,
    resolvida BOOLEAN NOT NULL DEFAULT FALSE,
    descricao_resolucao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pendencias_cliente_id ON "PENDENCIAS"(cliente_id);
CREATE INDEX IF NOT EXISTS idx_pendencias_funcionario_id ON "PENDENCIAS"(funcionario_id);
CREATE INDEX IF NOT EXISTS idx_pendencias_resolvida ON "PENDENCIAS"(resolvida);
