-- Create table for storing stock snapshots
CREATE TABLE IF NOT EXISTS "RELATORIO_DE_ESTOQUE" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_pedido BIGINT,
  data_hora_acerto TIMESTAMP WITH TIME ZONE,
  codigo_cliente BIGINT,
  cliente_nome TEXT,
  produto_nome TEXT,
  saldo_final NUMERIC,
  preco_vendido NUMERIC,
  estoque_por_produto NUMERIC,
  estoque_final NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create indices for performance
CREATE INDEX IF NOT EXISTS idx_relatorio_estoque_created_at ON "RELATORIO_DE_ESTOQUE" (created_at);
CREATE INDEX IF NOT EXISTS idx_relatorio_estoque_cliente ON "RELATORIO_DE_ESTOQUE" (codigo_cliente);
CREATE INDEX IF NOT EXISTS idx_relatorio_estoque_pedido ON "RELATORIO_DE_ESTOQUE" (numero_pedido);

-- RPC Function to calculate live stock data, save it as a snapshot, and return it
CREATE OR REPLACE FUNCTION process_and_save_stock_snapshot()
RETURNS TABLE (
  id BIGINT,
  numero_pedido BIGINT,
  data_hora_acerto TIMESTAMP WITH TIME ZONE,
  codigo_cliente BIGINT,
  cliente_nome TEXT,
  produto_nome TEXT,
  saldo_final NUMERIC,
  preco_vendido NUMERIC,
  estoque_por_produto NUMERIC,
  estoque_final NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE
) LANGUAGE plpgsql AS $$
DECLARE
  v_batch_time TIMESTAMP WITH TIME ZONE := timezone('utc'::text, now());
BEGIN
  RETURN QUERY
  WITH latest_orders_ids AS (
    SELECT DISTINCT ON ("CÓDIGO DO CLIENTE")
      "CÓDIGO DO CLIENTE" as client_id,
      "NÚMERO DO PEDIDO" as order_id
    FROM "BANCO_DE_DADOS"
    WHERE "NÚMERO DO PEDIDO" IS NOT NULL 
      AND "CÓDIGO DO CLIENTE" IS NOT NULL
    ORDER BY "CÓDIGO DO CLIENTE", "DATA DO ACERTO" DESC, "HORA DO ACERTO" DESC
  ),
  live_data AS (
    SELECT
      b."NÚMERO DO PEDIDO" as np,
      CASE
        WHEN b."DATA E HORA" IS NOT NULL AND b."DATA E HORA" != '' THEN b."DATA E HORA"::timestamp with time zone
        ELSE (b."DATA DO ACERTO" || ' ' || COALESCE(NULLIF(b."HORA DO ACERTO", ''), '00:00:00'))::timestamp with time zone
      END as dha,
      b."CÓDIGO DO CLIENTE" as cc,
      b.CLIENTE as cn,
      b.MERCADORIA as pn,
      COALESCE(b."SALDO FINAL", 0) as sf,
      CASE
          WHEN b."PREÇO VENDIDO" IS NULL OR b."PREÇO VENDIDO" = '' THEN 0
          WHEN b."PREÇO VENDIDO" ~ '^[0-9.]+,[0-9]+$' THEN CAST(REPLACE(REPLACE(b."PREÇO VENDIDO", '.', ''), ',', '.') AS NUMERIC)
          WHEN b."PREÇO VENDIDO" ~ '^[0-9,]+$' THEN CAST(REPLACE(b."PREÇO VENDIDO", ',', '.') AS NUMERIC)
          WHEN b."PREÇO VENDIDO" ~ '^[0-9.]+$' THEN CAST(b."PREÇO VENDIDO" AS NUMERIC)
          ELSE 0
      END as pv
    FROM "BANCO_DE_DADOS" b
    JOIN latest_orders_ids lo ON lo.order_id = b."NÚMERO DO PEDIDO" AND lo.client_id = b."CÓDIGO DO CLIENTE"
  ),
  calculated AS (
    SELECT
      ld.np,
      ld.dha,
      ld.cc,
      ld.cn,
      ld.pn,
      ld.sf,
      ld.pv,
      (ld.sf * ld.pv) as epp,
      SUM(ld.sf * ld.pv) OVER (PARTITION BY ld.np) as ef
    FROM live_data ld
  ),
  inserted AS (
    INSERT INTO "RELATORIO_DE_ESTOQUE" (
      numero_pedido, data_hora_acerto, codigo_cliente, cliente_nome, 
      produto_nome, saldo_final, preco_vendido, estoque_por_produto, estoque_final, created_at
    )
    SELECT 
      np, dha, cc, cn, pn, sf, pv, epp, ef, v_batch_time
    FROM calculated
    RETURNING *
  )
  SELECT 
    i.id, i.numero_pedido, i.data_hora_acerto, i.codigo_cliente, i.cliente_nome, 
    i.produto_nome, i.saldo_final, i.preco_vendido, i.estoque_por_produto, i.estoque_final, i.created_at
  FROM inserted i;
END;
$$;
