-- Create table for auditing Initial Balance adjustments
CREATE TABLE IF NOT EXISTS "public"."AJUSTE_SALDO_INICIAL" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "numero_pedido" BIGINT,
    "cliente_id" BIGINT NOT NULL,
    "cliente_nome" TEXT,
    "vendedor_id" BIGINT,
    "vendedor_nome" TEXT,
    "data_acerto" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "saldo_anterior" NUMERIC(10, 2),
    "saldo_novo" NUMERIC(10, 2),
    "quantidade_alterada" NUMERIC(10, 2),
    "produto_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure permissions
ALTER TABLE "public"."AJUSTE_SALDO_INICIAL" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON "public"."AJUSTE_SALDO_INICIAL"
AS PERMISSIVE FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert access for authenticated users" ON "public"."AJUSTE_SALDO_INICIAL"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (true);

-- Ensure BANCO_DE_DADOS ID VENDA ITENS is identity if not already
-- This block attempts to safely convert the column to IDENTITY if it isn't one
DO $$
BEGIN
    -- Only proceed if the column exists and isn't already an identity column
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'BANCO_DE_DADOS' 
        AND column_name = 'ID VENDA ITENS' 
        AND is_identity = 'NO'
    ) THEN
        -- Drop default if exists (e.g. sequence default)
        ALTER TABLE "public"."BANCO_DE_DADOS" ALTER COLUMN "ID VENDA ITENS" DROP DEFAULT;
        
        -- Add identity
        ALTER TABLE "public"."BANCO_DE_DADOS" ALTER COLUMN "ID VENDA ITENS" 
        ADD GENERATED BY DEFAULT AS IDENTITY;
        
        -- Sync sequence
        EXECUTE 'SELECT setval(pg_get_serial_sequence(''"public"."BANCO_DE_DADOS"'', ''ID VENDA ITENS''), COALESCE(MAX("ID VENDA ITENS"), 0) + 1, false) FROM "public"."BANCO_DE_DADOS"';
    END IF;
END $$;
