-- Create table for storing detailed final stock quantity
CREATE TABLE IF NOT EXISTS "QUANTIDADE DE ESTOQUE FINAL" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NUMERO DO PEDIDO" BIGINT,
  "DATA E HORA DO ACERTO" TIMESTAMP WITH TIME ZONE,
  "CÓDIGO DO CLIENTE" BIGINT,
  "CLIENTE" TEXT,
  "CÓDIGO DO PRODUTO" BIGINT,
  "MERCADORIA" TEXT,
  "SALDO FINAL" NUMERIC,
  "PREÇO VENDIDO" NUMERIC,
  "VALOR ESTOQUE POR PRODUTO" NUMERIC,
  "VALOR ESTOQUE SALDO FINAL" NUMERIC
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_qef_pedido ON "QUANTIDADE DE ESTOQUE FINAL" ("NUMERO DO PEDIDO");
CREATE INDEX IF NOT EXISTS idx_qef_cliente ON "QUANTIDADE DE ESTOQUE FINAL" ("CÓDIGO DO CLIENTE");
CREATE INDEX IF NOT EXISTS idx_qef_data ON "QUANTIDADE DE ESTOQUE FINAL" ("DATA E HORA DO ACERTO");

-- Populate the table using data from BANCO_DE_DADOS with calculations
-- Clear existing data to avoid duplicates if re-running
TRUNCATE TABLE "QUANTIDADE DE ESTOQUE FINAL";

INSERT INTO "QUANTIDADE DE ESTOQUE FINAL" (
  "NUMERO DO PEDIDO",
  "DATA E HORA DO ACERTO",
  "CÓDIGO DO CLIENTE",
  "CLIENTE",
  "CÓDIGO DO PRODUTO",
  "MERCADORIA",
  "SALDO FINAL",
  "PREÇO VENDIDO",
  "VALOR ESTOQUE POR PRODUTO",
  "VALOR ESTOQUE SALDO FINAL"
)
WITH raw_data AS (
  SELECT
    "NÚMERO DO PEDIDO" as pedido,
    CASE
      WHEN NULLIF("DATA E HORA", '') IS NOT NULL THEN NULLIF("DATA E HORA", '')::timestamp with time zone
      ELSE (NULLIF("DATA DO ACERTO", '') || ' ' || COALESCE(NULLIF("HORA DO ACERTO", ''), '00:00:00'))::timestamp with time zone
    END as data_hora,
    "CÓDIGO DO CLIENTE" as cod_cliente,
    "CLIENTE" as nome_cliente,
    "COD. PRODUTO" as cod_produto,
    "MERCADORIA" as mercadoria,
    COALESCE("SALDO FINAL", 0) as saldo_final,
    CASE
        WHEN "PREÇO VENDIDO" IS NULL OR "PREÇO VENDIDO" = '' THEN 0
        WHEN "PREÇO VENDIDO" ~ '^[0-9.]+,[0-9]+$' THEN CAST(REPLACE(REPLACE("PREÇO VENDIDO", '.', ''), ',', '.') AS NUMERIC)
        WHEN "PREÇO VENDIDO" ~ '^[0-9,]+$' THEN CAST(REPLACE("PREÇO VENDIDO", ',', '.') AS NUMERIC)
        WHEN "PREÇO VENDIDO" ~ '^[0-9.]+$' THEN CAST("PREÇO VENDIDO" AS NUMERIC)
        ELSE 0
    END as preco_vendido_num
  FROM "BANCO_DE_DADOS"
  WHERE "NÚMERO DO PEDIDO" IS NOT NULL
),
calc_data AS (
  SELECT
    pedido,
    data_hora,
    cod_cliente,
    nome_cliente,
    cod_produto,
    mercadoria,
    saldo_final,
    preco_vendido_num,
    (saldo_final * preco_vendido_num) as val_produto,
    SUM(saldo_final * preco_vendido_num) OVER (PARTITION BY pedido) as val_total_pedido
  FROM raw_data
)
SELECT
  pedido,
  data_hora,
  cod_cliente,
  nome_cliente,
  cod_produto,
  mercadoria,
  saldo_final,
  preco_vendido_num,
  val_produto,
  val_total_pedido
FROM calc_data;
