CREATE TABLE PERMISSOES (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setor TEXT NOT NULL,
  modulo TEXT NOT NULL,
  acesso BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(setor, modulo)
);

-- Insert default permissions for common sectors
INSERT INTO PERMISSOES (setor, modulo, acesso)
SELECT s.setor, m.modulo, TRUE
FROM (VALUES ('Vendedor'), ('Estoque'), ('Motoqueiro'), ('Financeiro')) as s(setor)
CROSS JOIN (VALUES 
  ('Clientes'), ('Funcionários'), ('Produtos'), ('Acerto'), 
  ('Recebimento'), ('Pix'), ('Cobrança'), ('Nota Fiscal'), 
  ('Caixa'), ('Inventário'), ('Rota'), ('Resumo Acertos'), 
  ('Relatório'), ('Pendências'), ('Backup')
) as m(modulo)
ON CONFLICT DO NOTHING;
