ALTER TABLE "public"."PRODUTOS" ALTER COLUMN "CÓDIGO BARRAS" TYPE TEXT USING "CÓDIGO BARRAS"::TEXT;
ALTER TABLE "public"."PRODUTOS" ALTER COLUMN "codigo_interno" TYPE TEXT USING "codigo_interno"::TEXT;
